# Setup
title:               Leon Williams
tagline:             'Leon Williams'
description:         'A website for displaying the work I have done and the work I am doing.'
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Leon Williams
  url:               www.github.com/leonbaiyu
  email:             leonbaiyu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
